apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: todo-backend
    {{- include "todo-chatbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
      nodePort: {{ .Values.backend.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: todo-backend
