apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: todo-frontend
    {{- include "todo-chatbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.frontend.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: todo-frontend
