apiVersion: v1
kind: Service
metadata:
  name: todo-mcp
  namespace: {{ .Values.namespace }}
  labels:
    app: todo-mcp
    {{- include "todo-chatbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mcp.service.type }}
  ports:
    - port: {{ .Values.mcp.service.port }}
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: todo-mcp
